/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademiaRouteImport } from './routes/academia'
import { Route as AdvogadosRouteImport } from './routes/advogados'
import { Route as BarbeariaRouteImport } from './routes/barbearia'
import { Route as CafeteriaRouteImport } from './routes/cafeteria'
import { Route as ClinicasRouteImport } from './routes/clinicas'
import { Route as ConsultorioRouteImport } from './routes/consultorio'
import { Route as DesignRouteImport } from './routes/design'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as EscolaRouteImport } from './routes/escola'
import { Route as ImobiliariaRouteImport } from './routes/imobiliaria'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as RestauranteRouteImport } from './routes/restaurante'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaRoute = AcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadosRoute = AdvogadosRouteImport.update({
  id: '/advogados',
  path: '/advogados',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbeariaRoute = BarbeariaRouteImport.update({
  id: '/barbearia',
  path: '/barbearia',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeteriaRoute = CafeteriaRouteImport.update({
  id: '/cafeteria',
  path: '/cafeteria',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicasRoute = ClinicasRouteImport.update({
  id: '/clinicas',
  path: '/clinicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorioRoute = ConsultorioRouteImport.update({
  id: '/consultorio',
  path: '/consultorio',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolaRoute = EscolaRouteImport.update({
  id: '/escola',
  path: '/escola',
  getParentRoute: () => rootRouteImport,
} as any)
const ImobiliariaRoute = ImobiliariaRouteImport.update({
  id: '/imobiliaria',
  path: '/imobiliaria',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const RestauranteRoute = RestauranteRouteImport.update({
  id: '/restaurante',
  path: '/restaurante',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/advogados': typeof AdvogadosRoute
  '/barbearia': typeof BarbeariaRoute
  '/cafeteria': typeof CafeteriaRoute
  '/clinicas': typeof ClinicasRoute
  '/consultorio': typeof ConsultorioRoute
  '/design': typeof DesignRoute
  '/ecommerce': typeof EcommerceRoute
  '/escola': typeof EscolaRoute
  '/imobiliaria': typeof ImobiliariaRoute
  '/loja': typeof LojaRoute
  '/restaurante': typeof RestauranteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/advogados': typeof AdvogadosRoute
  '/barbearia': typeof BarbeariaRoute
  '/cafeteria': typeof CafeteriaRoute
  '/clinicas': typeof ClinicasRoute
  '/consultorio': typeof ConsultorioRoute
  '/design': typeof DesignRoute
  '/ecommerce': typeof EcommerceRoute
  '/escola': typeof EscolaRoute
  '/imobiliaria': typeof ImobiliariaRoute
  '/loja': typeof LojaRoute
  '/restaurante': typeof RestauranteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academia': typeof AcademiaRoute
  '/advogados': typeof AdvogadosRoute
  '/barbearia': typeof BarbeariaRoute
  '/cafeteria': typeof CafeteriaRoute
  '/clinicas': typeof ClinicasRoute
  '/consultorio': typeof ConsultorioRoute
  '/design': typeof DesignRoute
  '/ecommerce': typeof EcommerceRoute
  '/escola': typeof EscolaRoute
  '/imobiliaria': typeof ImobiliariaRoute
  '/loja': typeof LojaRoute
  '/restaurante': typeof RestauranteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academia'
    | '/advogados'
    | '/barbearia'
    | '/cafeteria'
    | '/clinicas'
    | '/consultorio'
    | '/design'
    | '/ecommerce'
    | '/escola'
    | '/imobiliaria'
    | '/loja'
    | '/restaurante'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academia'
    | '/advogados'
    | '/barbearia'
    | '/cafeteria'
    | '/clinicas'
    | '/consultorio'
    | '/design'
    | '/ecommerce'
    | '/escola'
    | '/imobiliaria'
    | '/loja'
    | '/restaurante'
  id:
    | '__root__'
    | '/'
    | '/academia'
    | '/advogados'
    | '/barbearia'
    | '/cafeteria'
    | '/clinicas'
    | '/consultorio'
    | '/design'
    | '/ecommerce'
    | '/escola'
    | '/imobiliaria'
    | '/loja'
    | '/restaurante'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademiaRoute: typeof AcademiaRoute
  AdvogadosRoute: typeof AdvogadosRoute
  BarbeariaRoute: typeof BarbeariaRoute
  CafeteriaRoute: typeof CafeteriaRoute
  ClinicasRoute: typeof ClinicasRoute
  ConsultorioRoute: typeof ConsultorioRoute
  DesignRoute: typeof DesignRoute
  EcommerceRoute: typeof EcommerceRoute
  EscolaRoute: typeof EscolaRoute
  ImobiliariaRoute: typeof ImobiliariaRoute
  LojaRoute: typeof LojaRoute
  RestauranteRoute: typeof RestauranteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia': {
      id: '/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogados': {
      id: '/advogados'
      path: '/advogados'
      fullPath: '/advogados'
      preLoaderRoute: typeof AdvogadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbearia': {
      id: '/barbearia'
      path: '/barbearia'
      fullPath: '/barbearia'
      preLoaderRoute: typeof BarbeariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafeteria': {
      id: '/cafeteria'
      path: '/cafeteria'
      fullPath: '/cafeteria'
      preLoaderRoute: typeof CafeteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinicas': {
      id: '/clinicas'
      path: '/clinicas'
      fullPath: '/clinicas'
      preLoaderRoute: typeof ClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultorio': {
      id: '/consultorio'
      path: '/consultorio'
      fullPath: '/consultorio'
      preLoaderRoute: typeof ConsultorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola': {
      id: '/escola'
      path: '/escola'
      fullPath: '/escola'
      preLoaderRoute: typeof EscolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imobiliaria': {
      id: '/imobiliaria'
      path: '/imobiliaria'
      fullPath: '/imobiliaria'
      preLoaderRoute: typeof ImobiliariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurante': {
      id: '/restaurante'
      path: '/restaurante'
      fullPath: '/restaurante'
      preLoaderRoute: typeof RestauranteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademiaRoute: AcademiaRoute,
  AdvogadosRoute: AdvogadosRoute,
  BarbeariaRoute: BarbeariaRoute,
  CafeteriaRoute: CafeteriaRoute,
  ClinicasRoute: ClinicasRoute,
  ConsultorioRoute: ConsultorioRoute,
  DesignRoute: DesignRoute,
  EcommerceRoute: EcommerceRoute,
  EscolaRoute: EscolaRoute,
  ImobiliariaRoute: ImobiliariaRoute,
  LojaRoute: LojaRoute,
  RestauranteRoute: RestauranteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
